spring:
  h2:
    console:
      path: /h2           # h2 console ??
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create    # ??? ?? ??
    show-sql: true        # SQL ?? ??
    properties:
      hibernate:
        format_sql: true    # SQL ?? ??
